name: habbit_mobil_flutter
description: "A new Flutter project."

# Publicaci贸n
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Versi贸n de la aplicaci贸n
version: 1.0.0+1

# Entorno
environment:
  sdk: '>=3.3.4 <4.0.0'

# Dependencias
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_bottom_navigation_bar: 1.3.3
  flutter_animate: ^4.5.0
  go_router: ^14.1.4
  page_transition: ^2.0.8
  animations: ^2.0.0
  get: ^4.6.5
  lottie: ^3.1.2
  flutter_screenutil: ^5.9.3
  google_maps_flutter: ^2.6.1
  geocoding: ^3.0.0
  photo_view: ^0.15.0
  animated_splash_screen: ^1.3.0
  smooth_page_indicator: ^1.1.0
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  crypto: ^3.0.3
  provider: ^6.1.2
  animated_toggle_switch: ^0.8.2
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  rive: ^0.13.13
  shared_preferences: ^2.2.3


# Dependencias de desarrollo
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon.png"
  adaptive_icon_background: "#0D47A1"
  min_sdk_android: 21 # android min sdk min:16, default 21


# Configuraci贸n de Flutter
flutter:
  uses-material-design: true

  # Activos
  assets:
    - assets/images/
    - assets/rive/  
